'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class campaigns

    '''<summary>
    '''lblcampaignname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcampaignname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcampaignname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcampaignname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblmaildate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmaildate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmaildate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmaildate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbltemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltemplate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstboxtemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstboxtemplate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSaveCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCampaign As Global.System.Web.UI.WebControls.Button
End Class
